<a href="https://colab.research.google.com/github/MageNavneet/PyTorch/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals


In [81]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [82]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor`

In [83]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [84]:
scalar.ndim

0

In [85]:
# Get tensor back as Python int
scalar.item()

7

In [86]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [87]:
vector.ndim

1

In [88]:
vector.shape

torch.Size([2])

In [89]:
# Matrix

MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [90]:
MATRIX.ndim

2

In [91]:
MATRIX[1]

tensor([ 9, 10])

In [92]:
MATRIX.shape

torch.Size([2, 2])

In [93]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [94]:
TENSOR.ndim

3

In [95]:
TENSOR.shape

torch.Size([1, 3, 3])

In [96]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important beacuse the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update ranom numbers -> look at data -> upadate random numbers`

In [97]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1136, 0.6765, 0.8079, 0.6799],
        [0.8145, 0.2224, 0.2266, 0.9736],
        [0.4032, 0.0439, 0.9570, 0.6743]])

In [98]:
random_tensor.ndim

2

In [99]:
random_tensor.shape

torch.Size([3, 4])

In [100]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,  224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [101]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [102]:
# Creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [103]:
ones.dtype

torch.float32

In [104]:
random_tensor.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [105]:
# Use torch.range()
one_to_ten = torch.range(start=0,end=10, step=1)
one_to_ten

/tmp/ipython-input-105-530396212.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start=0,end=10, step=1)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [106]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [107]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16),
                               device=None, # what device is your tesnor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [108]:
float_32_tensor.dtype

torch.float32

In [109]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [110]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [111]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [112]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from the tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use4 `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [113]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3165, 0.5869, 0.7176, 0.6898],
        [0.3018, 0.6201, 0.6711, 0.8734],
        [0.3768, 0.9014, 0.5202, 0.8647]])

In [114]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [115]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3165, 0.5869, 0.7176, 0.6898],
        [0.3018, 0.6201, 0.6711, 0.8734],
        [0.3768, 0.9014, 0.5202, 0.8647]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtratcion
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [116]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3 ])
tensor + 10

tensor([11, 12, 13])

In [117]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [118]:
tensor

tensor([1, 2, 3])

In [119]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [120]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [121]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performing matrix multiplcaton needs to satisfy:
1. The **inner dimensions must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimesnions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [122]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

In [123]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))


tensor([[1.0871, 1.0312],
        [0.4319, 0.4029]])

In [124]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

In [125]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [126]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [127]:
tensor

tensor([1, 2, 3])

In [128]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [129]:
tensor @ tensor

tensor(14)

In [130]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.17 ms, sys: 30 µs, total: 1.2 ms
Wall time: 2.83 ms


In [131]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 55 µs, sys: 10 µs, total: 65 µs
Wall time: 70.8 µs


tensor(14)

### One of the most common errors in deep learning: shape errors


In [132]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as the troch.matmul (It's the alias for wirting less code)

In [133]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tesnor shape issues, we can manipulate the shape of one of our tensors using a ***transpose***.

A **transpose** switches the axes or dimensions of a given tensor.

In [134]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [135]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [136]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
torch.matmul(tensor_A, tensor_B.T)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [137]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [138]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [139]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [140]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [141]:
# Find the sum
torch.sum(x), x.sum( )

(tensor(450), tensor(450))

## FInding the positional min and max


In [142]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [143]:
# Find the position in tensor that has the minmum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [144]:
x[0]

tensor(0)

In [145]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [146]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tesnor to a defined shape
* View - Return a view of an input tensor of a certain shape but keeps the same memory
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to target tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [147]:
# Let's create a tensor
import torch
x = torch.arange(1, 10)
x, x.shape, x.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), torch.int64)

In [148]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
print(x_reshaped)
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [158]:
x = torch.arange(1., 11.)
print(f"shape: {x.shape}, dtype: {x.dtype}")
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

shape: torch.Size([10]), dtype: torch.float32


(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [150]:
# Change the view
z = x.view(1, 10) # z is just the different view of x. They share the same memory.
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [151]:
# Changing z changes x (because a view of a tensor shares the same memory as the orignal input)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [152]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [186]:
# torch.squeeze() -> removes all single dimensioms from a trarget tesnor
x_squeezed = x_reshaped.squeeze()
x = torch.arange(1, 10)
x_reshaped = x.reshape(1, 9)
x_reshaped
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tesnor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tesnor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


torch.Size([1, 9])

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

torch.Size([9])