<a href="https://colab.research.google.com/github/MageNavneet/PyTorch/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals


In [2]:
!nvidia-smi

Sat Jun 28 11:28:36 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor`

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix

MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important beacuse the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update ranom numbers -> look at data -> upadate random numbers`

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8244, 0.3266, 0.3771, 0.2677],
        [0.4612, 0.0619, 0.7267, 0.0381],
        [0.5817, 0.4240, 0.3712, 0.1553]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,  224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [26]:
# Use torch.range()
one_to_ten = torch.range(start=0,end=10, step=1)
one_to_ten

/tmp/ipython-input-26-530396212.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start=0,end=10, step=1)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16),
                               device=None, # what device is your tesnor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from the tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use4 `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [34]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6797, 0.5660, 0.5633, 0.1573],
        [0.6652, 0.7091, 0.9524, 0.5328],
        [0.3599, 0.6770, 0.9329, 0.2231]])

In [35]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [36]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.6797, 0.5660, 0.5633, 0.1573],
        [0.6652, 0.7091, 0.9524, 0.5328],
        [0.3599, 0.6770, 0.9329, 0.2231]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtratcion
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [37]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3 ])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [41]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performing matrix multiplcaton needs to satisfy:
1. The **inner dimensions must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimesnions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [82]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [83]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))


tensor([[0.3918, 0.2426],
        [0.5943, 0.4743]])

In [85]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

In [47]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [48]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
tensor

tensor([1, 2, 3])

In [78]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [79]:
tensor @ tensor

tensor(14)

In [70]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.24 ms, sys: 18 µs, total: 1.25 ms
Wall time: 1.14 ms


In [75]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 117 µs, sys: 9 µs, total: 126 µs
Wall time: 87.3 µs


tensor(14)