<a href="https://colab.research.google.com/github/MageNavneet/PyTorch/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals


In [7]:
!nvidia-smi

Sun Jul  6 04:01:50 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P8             13W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor`

In [9]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
# Get tensor back as Python int
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# Matrix

MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[1]

tensor([ 9, 10])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important beacuse the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update ranom numbers -> look at data -> upadate random numbers`

In [23]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3347, 0.7703, 0.3456, 0.0678],
        [0.1977, 0.7720, 0.1142, 0.1815],
        [0.2318, 0.3171, 0.4911, 0.6781]])

In [24]:
random_tensor.ndim

2

In [25]:
random_tensor.shape

torch.Size([3, 4])

In [26]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,  224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [27]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

In [30]:
random_tensor.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [31]:
# Use torch.range()
one_to_ten = torch.range(start=0,end=10, step=1)
one_to_ten

/tmp/ipython-input-31-530396212.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start=0,end=10, step=1)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [33]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16),
                               device=None, # what device is your tesnor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from the tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use4 `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7420, 0.0347, 0.4971, 0.9053],
        [0.4347, 0.3981, 0.5407, 0.6344],
        [0.4419, 0.6088, 0.3034, 0.2266]])

In [40]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [41]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.7420, 0.0347, 0.4971, 0.9053],
        [0.4347, 0.3981, 0.5407, 0.6344],
        [0.4419, 0.6088, 0.3034, 0.2266]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtratcion
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [42]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3 ])
tensor + 10

tensor([11, 12, 13])

In [43]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [46]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performing matrix multiplcaton needs to satisfy:
1. The **inner dimensions must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimesnions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [48]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

In [49]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))


tensor([[0.8420, 0.4747],
        [0.7720, 0.1699]])

In [50]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

In [51]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [52]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [53]:
tensor

tensor([1, 2, 3])

In [54]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [55]:
tensor @ tensor

tensor(14)

In [56]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 0 ns, sys: 584 µs, total: 584 µs
Wall time: 672 µs


In [57]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 36 µs, sys: 2 µs, total: 38 µs
Wall time: 42.4 µs


tensor(14)

### One of the most common errors in deep learning: shape errors


In [58]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as the troch.matmul (It's the alias for wirting less code)

In [59]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tesnor shape issues, we can manipulate the shape of one of our tensors using a ***transpose***.

A **transpose** switches the axes or dimensions of a given tensor.

In [60]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [61]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [62]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
torch.matmul(tensor_A, tensor_B.T)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [63]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [64]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [65]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [66]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [67]:
# Find the sum
torch.sum(x), x.sum( )

(tensor(450), tensor(450))

## FInding the positional min and max


In [68]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
# Find the position in tensor that has the minmum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [70]:
x[0]

tensor(0)

In [71]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [72]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tesnor to a defined shape
* View - Return a view of an input tensor of a certain shape but keeps the same memory
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to target tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [73]:
# Let's create a tensor
import torch
x = torch.arange(1, 10)
x, x.shape, x.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), torch.int64)

In [74]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
print(x_reshaped)
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [75]:
x = torch.arange(1., 11.)
print(f"shape: {x.shape}, dtype: {x.dtype}")
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

shape: torch.Size([10]), dtype: torch.float32


(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [76]:
# Change the view
z = x.view(1, 10) # z is just the different view of x. They share the same memory.
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [77]:
# Changing z changes x (because a view of a tensor shares the same memory as the orignal input)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [78]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [79]:
# torch.squeeze() -> removes all single dimensioms from a trarget tesnor
x_squeezed = x_reshaped.squeeze()
x = torch.arange(1, 10)
x_reshaped = x.reshape(1, 9)
x_reshaped
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tesnor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tesnor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [80]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
nNew tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [81]:
# torch.permute - rearrange the dimension of a target tensor in a specified order (shares the same memory as it's a way)
x_original = torch.rand(224, 224, 3) # [height, width, colour_channels)]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [82]:
x_original[0, 0, 0] = 729218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(729218.), tensor(729218.))

 ## Indexing (selecting data from tensors)

 Indexing with PyTorch is similar to indexing with NumPy.

In [83]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [84]:
# Let's index on our new tesnor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [85]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [86]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [87]:
# You can also use ":" to select "all" of a target dimesion
x[:, 0], x[0, 0]

(tensor([[1, 2, 3]]), tensor([1, 2, 3]))

In [88]:
# Get all values of 0th and first dimension but only indext 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [89]:
# Get all values of the 0 dimensions but only index 1 and 2nd dimension
x[:, 1, 1]

tensor([5])

In [90]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [91]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientic Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch  tensor -> NumPy -> `torch.Tensor.numpy()`

In [92]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: when converting from numpy -> pytorch, pytorch reflec ts numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [93]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [95]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 2
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the ranodm seed does is "flavour" the randomness.


In [96]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7632, 0.1902, 0.4186, 0.9588],
        [0.8618, 0.4150, 0.9276, 0.9645],
        [0.7780, 0.2786, 0.5666, 0.2555]])
tensor([[0.9772, 0.4519, 0.6335, 0.4143],
        [0.6376, 0.0035, 0.2049, 0.4937],
        [0.3921, 0.5602, 0.2536, 0.2570]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [97]:
# Let's make some random but reproducible tensors
import torch
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU.
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

In [98]:
!nvidia-smi

Sun Jul  6 04:01:51 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P8             13W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [99]:
# Check for the GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [100]:
# Setup device agnostic code
device = "cuda"if torch.cuda.is_available() else "cpu"
device

'cuda'

In [101]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want tensors/models on the GPU is because using a GPU results in faster computations.


In [104]:
# Creare a tensor (default on the GPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [106]:
# Mover tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [108]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()

In [109]:
# To fix the GPU tesnor with NumPy issue, we can first set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [110]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')